spring:
  application:
    name: ${springboot.app.name:gateway-service}

info:
  component: Edge Server
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  prefix: /v1
#  ignoredServices: '*'
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  routes:
    tax:
      path: /tax-api/**
      sensitiveHeaders:
      serviceId: tax-service
    item:
      path: /item-api/**
      sensitiveHeaders:
      serviceId: item-service
    order:
      path: /order-api/**
      sensitiveHeaders:
      serviceId: order-service
    customer: 
      path: /customer-api/**
      sensitiveHeaders:
      serviceId: customer-service
    authentication:
      path: /authentication-api/**
      sensitiveHeaders:
      serviceId: authentication-service

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000


eureka:
  client:
    serviceUrl:
      defaultZone: http://${registry.host:localhost}:${registry.port:8761}/eureka/
    registerWithEureka: false

      
server:
  port: 8765

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG